### ISSUE TITLE
Crashes when trying to condense AC3-Audio

### ISSUE THREAD

**Issue by CroakingToadElf** [ercanserteli/video-condenser#18]
Hey,

first of all, thanks a lot for this awesome piece of software, I love it.

However, I have a recurring problem, where it crashes whenever I try to condense an file that has AC3 audio. 
Other formats seem to work fine, but I can't handle AC3.
I have tried versions 1.5 and 1.6, nothing works.

Is it fixable? If so, it would be a blessing.

Anyway, thanks a lot for your hard work!

**Comment by ercanserteli** [comment]
Thank you for your kind words. I couldn't reproduce this. Can you check the log.txt in the executable directory for error messages, or run the exe through command line to keep the console window open and check the messages there? Also it would help if you can share a problematic file sample

**Comment by CroakingToadElf** [comment]
Here is the log file:

2024-12-11 00:01:36 - F:\4. Anime - Cartoon\[1.]MIP\[1.] Finished\Tales of Zestiria The X S1+S2 [Dual Audio][BD][1080p][HEVC 10bit x265][AAC][English Sub][Anime Time]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
not enough values to unpack (expected 2, got 0)
Traceback:
Traceback (most recent call last):
  File "condenser.py", line 494, in main
ValueError: not enough values to unpack (expected 2, got 0)


2024-12-11 00:01:46 - F:\4. Anime - Cartoon\[1.]MIP\[1.] Finished\Tales of Zestiria The X S1+S2 [Dual Audio][BD][1080p][HEVC 10bit x265][AAC][English Sub][Anime Time]\Tales of Zestiria the X
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Could not extract subtitle with ffmpeg: b'[sost#0:0/srt @ 000001ed9e6a19c0] Subtitle encoding currently only possible from text to text or bitmap to bitmap\r\nError opening output file C:\\Users\\amirs\\AppData\\Local\\Temp\\condenser_temp-1733871703664\\out.srt.\r\nError opening output files: Invalid argument\r\n'
Traceback:
Traceback (most recent call last):
  File "condenser.py", line 531, in main
  File "condenser.py", line 393, in condense_multi
  File "condenser.py", line 241, in extract_srt
Exception: Could not extract subtitle with ffmpeg: b'[sost#0:0/srt @ 000001ed9e6a19c0] Subtitle encoding currently only possible from text to text or bitmap to bitmap\r\nError opening output file C:\\Users\\amirs\\AppData\\Local\\Temp\\condenser_temp-1733871703664\\out.srt.\r\nError opening output files: Invalid argument\r\n'
